### PR TITLE
 testclustertopology: scale out/in cluster(support tidb,pd,tikv)

### PR DESCRIPTION
**Pull request by CadmusJiang**
Signed-off-by: Cadmus <CadmusJiang@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
testclustertopology_types.go, testclustertopology_controller.go, tiup/deploy.go
How it Works:
1. controller check if cluster is scaling out/in.
2. call tiup commd(scale-out/scale-in) to finish scale.
3. testclustertopology webhook check yaml.
4. add global field, when components lack dataDir and deployDir, will use global instead
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
Set global once, not once
1.create request include n1,n2,n3
2.create cluster topology  tidb(n1,n2) tikv(n1,n2) pd(n1,n2)
3.scale-in tidb n2
4.scale-in tikv n2
5.scale-in pd n2
6.scale-out tidb to n3
7.scale-out tikv to n3
8.scale-out pd to n3

Side effects

- Breaking backward compatibility

### CODE REVIEW

**Review by mahjonp — APPROVED** [review]
lgtm

**Comment by Hexilee** [comment]
lgtm

**Comment by Hexilee** [comment]
@CadmusJiang Please fix the DeepSource issue.

**Comment by CadmusJiang** [comment]
> @CadmusJiang Please fix the DeepSource issue.

Unused code will be used in the future.

**Pull request closed without merging**
